
redis:
 image: redis
 
mongo: 
  image: mongo
 
nginx:
 build: ./nginx
 links:
  - demoappdev_node1:demoappdev_node1
  - demoappdev_node2:demoappdev_node2
  - demoappdev_node3:demoappdev_node3
 ports:
  - "80:80"

demoappdev_node1: 
 dockerfile: ProdDockerfile
 build: .
 links: 
  - redis
  - mongo
 ports:
  - "3000"
  
demoappdev_node2: 
 dockerfile: ProdDockerfile
 build: .
 links: 
  - redis
  - mongo
 ports:
  - "3000"
   
demoappdev_node3: 
 dockerfile: ProdDockerfile
 build: .
 links: 
  - redis
  - mongo
 ports:
  - "3000"