# Run "docker-compose --file ProdDocker-compose.yml up -d" to bring up the prod environment.
redis:
 image: redis

mongo:
  image: mongo

demoappdev:
 dockerfile: Dockerfile.prod
 build: .
 links:
  - redis
  - mongo
 ports:
  - "80:3000"
